import os
import json
import sqlite3
from collections.abc import Mapping
from flask import current_app, g

_db_initialized = False


class LibsqlRow(Mapping):
    def __init__(self, row, columns):
        self._row = row
        self._columns = columns
        self._col_map = {name: i for i, name in enumerate(columns)}

    def __getitem__(self, key):
        if isinstance(key, str):
            if key in self._col_map:
                return self._row[self._col_map[key]]
            raise KeyError(f"Column '{key}' not found in row")
        return self._row[key]

    def __iter__(self):
        return iter(self._columns)

    def __len__(self):
        return len(self._columns)

    def keys(self):
        return self._columns


class LibsqlCursor:
    def __init__(self, result_set):
        self.columns = result_set.columns
        self.rows = [LibsqlRow(row, self.columns) for row in result_set.rows]
        self._last_insert_rowid = result_set.last_insert_rowid
        self._index = 0

    @property
    def lastrowid(self):
        return self._last_insert_rowid

    def fetchone(self):
        if self._index < len(self.rows):
            row = self.rows[self._index]
            self._index += 1
            return row
        return None

    def fetchall(self):
        return self.rows


class LibsqlConnection:
    def __init__(self, client):
        self.client = client

    def execute(self, sql, parameters=None):
        if parameters is None:
            res = self.client.execute(sql)
        else:
            res = self.client.execute(sql, list(parameters))
        return LibsqlCursor(res)

    def commit(self):
        pass

    def rollback(self):
        pass

    def close(self):
        try:
            self.client.close()
        except Exception:
            pass

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()


class PgRow(dict):
    def __getitem__(self, key):
        if isinstance(key, int):
            keys = list(self.keys())
            return self[keys[key]]
        return super().__getitem__(key)


class PgCursor:
    def __init__(self, rows, columns, lastrowid=None, rowcount=0):
        self.rows = [PgRow(zip(columns, r)) for r in rows] if columns and rows else []
        self._index = 0
        self.lastrowid = lastrowid
        self.rowcount = rowcount

    def fetchone(self):
        if self._index < len(self.rows):
            row = self.rows[self._index]
            self._index += 1
            return row
        return None

    def fetchall(self):
        return self.rows


class PgConnection:
    def __init__(self, conn):
        self.conn = conn

    def execute(self, sql, parameters=None):
        if parameters is None:
            parameters = ()

        pg_sql = sql.replace("?", "%s")
        pg_sql = pg_sql.replace("INTEGER PRIMARY KEY AUTOINCREMENT", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
        
        if "PRAGMA table_info" in pg_sql or "PRAGMA journal_mode" in pg_sql or "PRAGMA synchronous" in pg_sql:
            return PgCursor([], [], rowcount=0)

        is_insert = pg_sql.strip().upper().startswith("INSERT")
        if is_insert and "RETURNING" not in pg_sql.upper():
            pg_sql = pg_sql.rstrip(";") + " RETURNING id;"

        cur = self.conn.cursor()
        cur.execute(pg_sql, list(parameters))

        lastrowid = None
        rows = []
        cols = []

        if cur.description:
            cols = [desc[0] for desc in cur.description]
            rows = cur.fetchall()
            if is_insert and rows and "id" in cols:
                lastrowid = rows[0][cols.index("id")]

        return PgCursor(rows, cols, lastrowid=lastrowid, rowcount=cur.rowcount)

    def commit(self):
        try:
            self.conn.commit()
        except Exception:
            pass

    def rollback(self):
        try:
            self.conn.rollback()
        except Exception:
            pass

    def close(self):
        try:
            self.conn.close()
        except Exception:
            pass

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if exc_type:
            self.rollback()
        else:
            self.commit()
        self.close()


def _create_tables_and_migrations(db):
    db.execute("""CREATE TABLE IF NOT EXISTS users (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        email TEXT NOT NULL UNIQUE,
        password_hash TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )""")
    try:
        columns = {row["name"] for row in db.execute("PRAGMA table_info(users)")}
        if "google_sub" not in columns:
            db.execute("ALTER TABLE users ADD COLUMN google_sub TEXT")
    except Exception as e:
        current_app.logger.warning(f"Migration error for users table: {e}")

    db.execute("""CREATE TABLE IF NOT EXISTS analyses (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id INTEGER NOT NULL,
        filename TEXT NOT NULL,
        job_description TEXT,
        overall_score INTEGER NOT NULL,
        dimension_scores TEXT NOT NULL,
        summary TEXT NOT NULL,
        strengths TEXT NOT NULL,
        weaknesses TEXT NOT NULL,
        missing_sections TEXT NOT NULL,
        ats_issues TEXT NOT NULL,
        suggestions TEXT NOT NULL,
        suggested_keywords TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )""")
    try:
        a_cols = {row["name"] for row in db.execute("PRAGMA table_info(analyses)")}
        if "full_json" not in a_cols:
            db.execute("ALTER TABLE analyses ADD COLUMN full_json TEXT")
        if "file_path" not in a_cols:
            db.execute("ALTER TABLE analyses ADD COLUMN file_path TEXT")
        if "content_hash" not in a_cols:
            db.execute("ALTER TABLE analyses ADD COLUMN content_hash TEXT")
    except Exception as e:
        current_app.logger.warning(f"Migration error for analyses table: {e}")


    db.execute("""CREATE TABLE IF NOT EXISTS oauth_states (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        state TEXT NOT NULL UNIQUE,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )""")

    db.execute("""CREATE TABLE IF NOT EXISTS rate_limits (
        key TEXT NOT NULL,
        window_start INTEGER NOT NULL,
        hits INTEGER NOT NULL DEFAULT 1,
        PRIMARY KEY (key, window_start)
    )""")

    db.execute("""CREATE TABLE IF NOT EXISTS resumes (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id INTEGER NOT NULL,
        title TEXT NOT NULL,
        filename TEXT,
        template TEXT NOT NULL DEFAULT 'modern',
        overall_score INTEGER DEFAULT 0,
        analysis_json TEXT,
        data_json TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    )""")
    try:
        r_cols = {row["name"] for row in db.execute("PRAGMA table_info(resumes)")}
        if "filename" not in r_cols:
            db.execute("ALTER TABLE resumes ADD COLUMN filename TEXT")
        if "overall_score" not in r_cols:
            db.execute("ALTER TABLE resumes ADD COLUMN overall_score INTEGER DEFAULT 0")
        if "analysis_json" not in r_cols:
            db.execute("ALTER TABLE resumes ADD COLUMN analysis_json TEXT")
        if "file_path" not in r_cols:
            db.execute("ALTER TABLE resumes ADD COLUMN file_path TEXT")
        if "file_size" not in r_cols:
            db.execute("ALTER TABLE resumes ADD COLUMN file_size INTEGER DEFAULT 0")
        if "mime_type" not in r_cols:
            db.execute("ALTER TABLE resumes ADD COLUMN mime_type TEXT DEFAULT 'application/pdf'")
    except Exception as e:
        current_app.logger.warning(f"Migration error for resumes table: {e}")


def store_oauth_state(state):
    db = get_db()
    try:
        db.execute(
            "INSERT INTO oauth_states (state) VALUES (?)",
            (state,)
        )
        db.commit()
    except Exception:
        pass


def verify_oauth_state(state):
    db = get_db()
    try:
        row = db.execute(
            "SELECT id FROM oauth_states WHERE state = ?",
            (state,)
        ).fetchone()
        if row:
            db.execute("DELETE FROM oauth_states WHERE id = ?", (row["id"],))
            db.commit()
            return True
    except Exception:
        pass
    return False


def cleanup_expired_oauth_states():
    try:
        db = get_db()
        db.execute(
            "DELETE FROM oauth_states WHERE created_at < datetime('now', '-15 minutes')"
        )
        db.commit()
    except Exception:
        pass


def get_db():
    global _db_initialized
    pg_url = os.environ.get("SUPABASE_DB_URL") or os.environ.get("DATABASE_URL")
    if pg_url:
        try:
            import pg8000.dbapi
            from urllib.parse import urlparse
            parsed = urlparse(pg_url)
            conn = pg8000.dbapi.connect(
                user=parsed.username or "postgres",
                password=parsed.password or "",
                host=parsed.hostname or "localhost",
                port=parsed.port or 5432,
                database=parsed.path.lstrip("/") or "postgres",
                ssl_context=True
            )
            return PgConnection(conn)
        except Exception as e:
            if current_app:
                current_app.logger.warning(f"Supabase PostgreSQL connection error: {e}")

    db_url = os.environ.get("TURSO_DATABASE_URL")
    auth_token = os.environ.get("TURSO_AUTH_TOKEN")

    if db_url:
        try:
            import libsql_client
            client = libsql_client.create_client_sync(url=db_url, auth_token=auth_token or "")
            db = LibsqlConnection(client)
            if not _db_initialized:
                try:
                    _create_tables_and_migrations(db)
                    _db_initialized = True
                except Exception as e:
                    current_app.logger.error(f"Error initializing Turso tables: {e}")
            return db
        except Exception as e:
            if current_app:
                current_app.logger.warning(f"Turso connection failed, falling back to SQLite: {e}")

    if os.environ.get("VERCEL"):
        db_path = "/tmp/resumeai.db"
    else:
        db_path = current_app.config["DATABASE"]

    if not os.environ.get("VERCEL"):
        try:
            os.makedirs(os.path.dirname(db_path), exist_ok=True)
        except Exception:
            pass

    db = sqlite3.connect(db_path, timeout=30.0)
    db.row_factory = sqlite3.Row
    try:
        db.execute("PRAGMA journal_mode=WAL")
        db.execute("PRAGMA synchronous=NORMAL")
    except Exception:
        pass

    if not _db_initialized:
        try:
            _create_tables_and_migrations(db)
            db.commit()
            _db_initialized = True
        except Exception as e:
            if current_app:
                current_app.logger.error(f"Error initializing SQLite tables: {e}")

    return db
