-- ========================================================
-- JobSpike PostgreSQL Schema Migration for Supabase
-- Designed for Flask Session Auth + Service Role Backend
-- ========================================================

-- 1. Users Table (Stores Flask Auth Users)
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  google_sub TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Resumes Table (With File Metadata & File Path)
CREATE TABLE IF NOT EXISTS public.resumes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  filename TEXT,
  file_path TEXT,
  file_size BIGINT DEFAULT 0,
  mime_type TEXT DEFAULT 'application/pdf',
  template TEXT DEFAULT 'modern',
  overall_score INT DEFAULT 0,
  analysis_json JSONB DEFAULT '{}'::jsonb,
  data_json JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Analyses History Table
CREATE TABLE IF NOT EXISTS public.analyses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  filename TEXT NOT NULL,
  file_path TEXT,
  job_description TEXT,
  overall_score INT NOT NULL,
  dimension_scores JSONB NOT NULL,
  summary TEXT NOT NULL,
  strengths JSONB NOT NULL,
  weaknesses JSONB NOT NULL,
  missing_sections JSONB NOT NULL,
  ats_issues JSONB NOT NULL,
  suggestions JSONB NOT NULL,
  suggested_keywords JSONB NOT NULL,
  full_json JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. OAuth States Table
CREATE TABLE IF NOT EXISTS public.oauth_states (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  state TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Automatic updated_at Trigger for Resumes
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_resumes_updated_at ON public.resumes;
CREATE TRIGGER update_resumes_updated_at
BEFORE UPDATE ON public.resumes
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- 6. Performance Indexes
CREATE INDEX IF NOT EXISTS idx_resumes_user_id ON public.resumes(user_id);
CREATE INDEX IF NOT EXISTS idx_analyses_user_id ON public.analyses(user_id);
CREATE INDEX IF NOT EXISTS idx_analyses_created_at ON public.analyses(created_at);
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
