"""Candidate company names for the keyless-ATS registry sweep.

These are CANDIDATES ONLY — nothing here is assumed to use any particular ATS.
build_ats_registry.py tests every generated slug against each platform's public
board endpoint and keeps only the ones that actually respond with live jobs.

Weighting follows the brief: India, SEA and the Middle East first, then
remote-friendly employers, then the wider global pool that hires into those
regions.
"""

# region tag -> company display names
CANDIDATES = {
    "in": [
        "Razorpay", "Zomato", "Swiggy", "Flipkart", "Meesho", "CRED", "Zerodha",
        "Groww", "PhonePe", "Paytm", "Ola", "Ola Electric", "OYO", "Dream11",
        "Zetwerk", "Udaan", "ShareChat", "Unacademy", "Vedantu", "Cultfit",
        "Lenskart", "Nykaa", "Delhivery", "Rapido", "Urban Company", "Porter",
        "BrowserStack", "Postman", "Freshworks", "Zoho", "Chargebee", "Hasura",
        "CleverTap", "MoEngage", "Innovaccer", "Darwinbox", "Whatfix", "Icertis",
        "MindTickle", "Gupshup", "Netcore", "Exotel", "Kaleyra", "Yellow ai",
        "Observe AI", "Uniphore", "SirionLabs", "HighRadius", "Zenoti", "Amagi",
        "Apna", "Jupiter", "Slice", "Khatabook", "BharatPe", "Pine Labs",
        "Juspay", "Cashfree", "Setu", "Zeta", "M2P Fintech", "Perfios", "Signzy",
        "LeadSquared", "Wingify", "Scaler", "Turing", "InMobi", "Glance",
        "Sprinklr", "Druva", "Netradyne", "Rubrik", "Nutanix", "Postman Labs",
        "Chargebee Inc", "Fractal Analytics", "Tiger Analytics", "Mu Sigma",
        "Quantiphi", "Tredence", "LatentView", "AbsolutData", "Cars24",
        "Spinny", "CarDekho", "Droom", "BlackBuck", "Licious", "Country Delight",
        "BigBasket", "Dunzo", "Zepto", "Blinkit", "Purplle", "Mamaearth",
        "boAt", "Noise", "Wakefit", "Pepperfry", "Ather Energy", "Bounce",
        "Yulu", "Chalo", "RedBus", "Ixigo", "MakeMyTrip", "Cleartrip",
        "Practo", "PharmEasy", "Tata 1mg", "Netmeds", "HealthifyMe", "Curefit",
        "Razorpay Software", "Acko", "Digit Insurance", "PolicyBazaar",
        "Turtlemint", "InsuranceDekho", "Coverfox", "Vymo", "Kissflow",
        "Zluri", "Rocketlane", "Atlan", "Locus", "Shiprocket", "Unicommerce",
        "Vinculum", "Increff", "Fareye", "Loconav", "Stellapps", "DeHaat",
        "Ninjacart", "WayCool", "Jumbotail", "ElasticRun", "Udaan India",
    ],
    "sea": [
        "Grab", "Gojek", "GoTo", "Tokopedia", "Traveloka", "Bukalapak", "Shopee",
        "Sea", "Carousell", "Ninja Van", "Lazada", "VNG", "Tiki", "MoMo",
        "Coda Payments", "Kredivo", "Xendit", "Ajaib", "Halodoc", "Glints",
        "StashAway", "Endowus", "Nium", "Thunes", "Aspire", "Advance AI",
        "Funding Societies", "Akulaku", "OVO", "Dana", "LinkAja", "Flip",
        "Sicepat", "Waresix", "Kargo", "eFishery", "Sayurbox", "TaniHub",
        "Bibit", "Stockbit", "Pintu", "Tokocrypto", "Sleekflow", "Kumu",
        "GCash", "Maya", "PayMongo", "Sprout Solutions", "Kalibrr",
        "First Circle", "Great Deals", "VinFast", "VinAI", "Sky Mavis",
        "Katalon", "Base vn", "Elsa Speak", "Trusting Social", "Circles Life",
        "Zenyum", "Doctor Anywhere", "Ryde", "Zilingo", "Property Guru",
        "Bolttech", "Igloo", "Silot", "Validus", "Anext", "Atome",
    ],
    "me": [
        "Careem", "Talabat", "Noon", "Tabby", "Tamara", "Swvl", "Vezeeta",
        "Fawry", "Halan", "Trella", "Property Finder", "Bayut", "Dubizzle",
        "Anghami", "Kitopi", "Yassir", "Jahez", "Foodics", "Unifonic",
        "Mrsool", "Rain", "Lean Technologies", "Sary", "Nana", "Salla", "Zid",
        "Hala", "Barq", "Paymob", "Valu", "Khazna", "Breadfast", "Rabbit",
        "Instabug", "Bosta", "Homzmart", "Elmenus", "Nawy", "Yalla",
        "Chalhoub", "Alef Education", "Bayzat", "Sarwa", "Baraka", "Wio",
        "Ziina", "Pyypl", "Telr", "Network International", "Astra Tech",
        "Alba", "Floward", "Tarabut", "Nymcard", "Geidea", "Hyperpay",
    ],
    "remote": [
        "GitLab", "Automattic", "Zapier", "Doist", "Buffer", "Hotjar", "Toggl",
        "Remote", "Oyster", "Deel", "Toptal", "Andela", "Crossover", "Aha",
        "Close", "Sourcegraph", "Grafana Labs", "HashiCorp", "Elastic",
        "Canonical", "Mozilla", "DuckDuckGo", "Ghost", "Sentry", "PostHog",
        "Supabase", "Vercel", "Netlify", "Railway", "Render", "Fly", "Linear",
        "Notion", "Figma", "Miro", "Airtable", "Retool", "Webflow",
        "Contentful", "Strapi", "Prisma", "Cloudflare", "Twilio", "Stripe",
        "Shopify", "Coinbase", "Kraken", "Binance", "Bitpanda", "N26",
        "Revolut", "Wise", "Monzo", "Starling Bank", "Klarna", "Adyen",
        "Mollie", "Checkout", "Rapyd", "Airwallex", "Xero", "Atlassian",
        "Canva", "SafetyCulture", "Culture Amp", "Employment Hero", "Deputy",
        "Octopus Deploy", "Immutable", "Airwallex Global", "Typeform",
        "Paddle", "Pipedrive", "Bolt", "Glovo", "Wolt", "Delivery Hero",
        "Personio", "Celonis", "Trade Republic", "Flink", "Gorillas", "Zalando",
        "SumUp", "GetYourGuide", "Babbel", "Contentsquare", "Alan", "Qonto",
        "Swile", "Payfit", "Sorare", "Doctolib", "Back Market", "ManoMano",
        "Ledger", "Dataiku", "Mirakl", "Algolia", "Datadog", "Snyk", "Wiz",
        "Rippling", "Gusto", "Brex", "Ramp", "Mercury", "Plaid", "Modern Treasury",
        "Vanta", "Cohere", "OpenAI", "Anthropic", "Scale AI", "Weights and Biases",
        "Hugging Face", "Replicate", "Modal", "Together AI", "Perplexity",
        "Databricks", "Confluent", "dbt Labs", "Fivetran", "Airbyte", "Census",
        "Hightouch", "Amplitude", "Mixpanel", "Segment", "Braze", "Iterable",
        "Customer io", "Intercom", "Front", "Zendesk", "Freshdesk", "Help Scout",
        "Discourse", "Chili Piper", "Lattice", "Culture", "15Five", "Bamboo HR",
        "Workato", "Tray", "Make", "n8n", "Temporal", "Chainguard", "Tailscale",
        "1Password", "Bitwarden", "Proton", "Nord Security", "Surfshark",
    ],
    "global": [
        "Airbnb", "Dropbox", "DoorDash", "Instacart", "Lyft", "Pinterest",
        "Reddit", "Discord", "Robinhood", "Affirm", "Chime", "Marqeta",
        "Toast", "Flexport", "Samsara", "Verkada", "Rivian", "Lucid",
        "Palantir", "Spotify", "Match Group", "Wayfair", "Etsy", "Peloton",
        "Unity", "Roblox", "Epic Games", "Riot Games", "Ubisoft", "Bosch",
        "Siemens", "Philips", "Nestle", "Unilever", "Novartis", "Roche",
        "AstraZeneca", "Schneider Electric", "ABB", "Ericsson", "Nokia",
        "Volvo", "Scania", "IKEA", "Spotify Technology", "King", "Klarna Bank",
        "McDonalds", "Visa", "Mastercard", "PayPal", "Block", "Intuit",
        "ServiceNow", "Snowflake", "MongoDB", "Redis", "Neo4j", "Couchbase",
        "JFrog", "Sisense", "Similarweb", "Monday", "Wix", "Lightricks",
        "Papaya Global", "Riskified", "Forter", "Gong", "Walkme", "Taboola",
        "Outbrain", "Playtika", "Fiverr", "Lemonade", "eToro", "Payoneer",
    ],
    "in_expanded": [
        "Sprinto",
        "Plum",
        "Onsurity",
        "Nirvana",
        "Epifi",
        "Fi Money",
        "Jar",
        "FamPay",
        "Rupeek",
        "KreditBee",
        "MoneyView",
        "Navi",
        "Fibe",
        "Axio",
        "Stashfin",
        "Indifi",
        "Lendingkart",
        "Aye Finance",
        "Vivriti",
        "Yubi",
        "Credgenics",
        "FinBox",
        "Bureau",
        "IDfy",
        "HyperVerge",
        "Skyflow",
        "Refyne",
        "Jodo",
        "Leap Finance",
        "Eduvanz",
        "Propelld",
        "GradRight",
        "Masai School",
        "AlmaBetter",
        "Coding Ninjas",
        "Physics Wallah",
        "Testbook",
        "Adda247",
        "Doubtnut",
        "Teachmint",
        "Classplus",
        "Filo",
        "Emeritus",
        "upGrad",
        "Great Learning",
        "Simplilearn",
        "Newton School",
        "Rocketlane",
        "SquadStack",
        "Toplyne",
        "DevRev",
        "Slintel",
        "Kylas",
        "Locobuzz",
        "WebEngage",
        "Plotline",
        "Zenskar",
        "Nanonets",
        "Haptik",
        "Verloop",
        "Gnani",
        "Skit",
        "Krutrim",
        "Sarvam AI",
        "CoRover",
        "Mad Street Den",
        "Entropik",
        "Kapture",
        "Ozonetel",
        "Knowlarity",
        "Tata Digital",
        "Jio",
        "Meesho Technologies",
        "Udaan Com",
        "Bijnis",
        "OfBusiness",
        "Moglix",
        "Infra Market",
        "Zetwerk Manufacturing",
        "Cashify",
        "Yulu Bikes",
        "BluSmart",
        "Euler Motors",
        "Log9",
        "Battery Smart",
        "Chargezone",
        "Statiq",
        "Simple Energy",
        "Ultraviolette",
        "Matter",
        "River Mobility",
        "Vecmocon",
        "Exponent Energy",
        "Sun Mobility",
        "Zypp Electric",
        "Turno",
        "Altigreen",
        "Pixxel",
        "Skyroot",
        "Agnikul",
        "Dhruva Space",
        "Bellatrix",
        "Digantara",
        "GalaxEye",
        "Astrogate",
        "Tonbo Imaging",
        "ideaForge",
        "NewSpace",
        "Sastra Robotics",
        "Niramai",
        "Qure ai",
        "SigTuple",
        "Tricog",
        "Dozee",
        "Wysa",
        "Mfine",
        "DocsApp",
        "Medibuddy",
        "Pristyn Care",
        "Cure Foods",
        "Rebel Foods",
        "Chaayos",
        "Third Wave Coffee",
        "Blue Tokai",
        "Sleepy Owl",
        "Bombay Shaving",
        "Beardo",
        "Sugar Cosmetics",
        "Minimalist",
        "Plum Goodness",
        "Wow Skin",
        "MCaffeine",
        "Bewakoof",
        "Snitch",
        "Rare Rabbit",
        "Zouk",
        "Bluestone",
        "CaratLane",
        "Melorra",
        "GIVA",
        "Ajio",
        "Tata Cliq",
        "Firstcry",
        "Hopscotch",
        "SuperOps",
        "Atomicwork",
        "Hyperface",
        "Decentro",
        "Cashfree Payments",
        "Razorpay Technologies",
        "Open Financial",
        "Karbon",
        "RazorpayX",
        "Fold Money",
        "Stable Money",
        "Wint Wealth",
        "Grip Invest",
        "Tap Invest",
        "Dezerv",
        "Smallcase",
        "Sensibull",
        "Streak",
        "Tijori",
        "Finology",
        "INDmoney",
        "Angel One",
        "Upstox",
        "Dhan",
        "Fyers",
        "Alice Blue",
        "Motilal Oswal",
    ],
    "sea_expanded": [
        "Carro",
        "Carsome",
        "ShopBack",
        "Osome",
        "Sleek",
        "Patsnap",
        "Syfe",
        "Tiger Brokers",
        "Longbridge",
        "Bitkub",
        "Ascend Money",
        "LINE MAN Wongnai",
        "Pomelo Fashion",
        "Omise",
        "2C2P",
        "Flash Express",
        "Deliveree",
        "Shipper",
        "Sirclo",
        "Mekari",
        "Amartha",
        "Investree",
        "KoinWorks",
        "Julo",
        "Easycash",
        "UangMe",
        "Ruangguru",
        "Zenius Education",
        "Sampingan",
        "Pahamify",
        "Aerodyne",
        "MoneyLion",
        "BigPay",
        "StoreHub",
        "Involve Asia",
        "Setel",
        "Touch n Go",
        "Coc Coc",
        "KiotViet",
        "Sapo",
        "VNPay",
        "ZaloPay",
        "TymeX",
        "Got It",
        "Growsari",
        "Etaily",
        "Advance PH",
        "Peddlr",
        "Packworks",
        "Ninja Van Group",
        "J&T Express",
        "Ampverse",
        "Ryde Group",
        "Tapway",
        "Supahands",
        "Kenangan",
        "Kopi Kenangan",
        "Fore Coffee",
        "Segari",
        "Astro",
        "Dagangan",
        "Broom",
        "Komunal",
        "Xurya",
        "Rey Assurance",
        "Qoala",
        "PasarPolis",
        "Fuse",
        "Lifepal",
    ],
    "me_expanded": [
        "Huspy",
        "Alaan",
        "Pemo",
        "Cafu",
        "Yap",
        "Aramex",
        "Majid Al Futtaim",
        "Landmark Group",
        "Alshaya",
        "GMG",
        "Talabat Middle East",
        "HungerStation",
        "Rasan",
        "Nuwa",
        "Mozn",
        "Elm",
        "Thiqah",
        "stc pay",
        "Sadeem",
        "Yodawy",
        "Sylndr",
        "Cartona",
        "MaxAB",
        "Brimore",
        "Capiter",
        "Milezmore",
        "Odiggo",
        "Shahry",
        "Amenli",
        "Money Fellows",
        "Dopay",
        "Kashat",
        "Tasaheel",
        "Aqarmap",
        "Wuzzuf",
        "Bosta Egypt",
        "Trella Logistics",
        "Illa",
        "Nowlun",
        "Bekia",
        "Mumm",
        "Jumia",
        "Wasla",
        "Vezeeta Health",
        "Chefaa",
        "Rology",
        "Almentor",
        "Nagwa",
        "Zedny",
        "Andalusia",
        "Cleopatra",
        "Baraka Financial",
        "Sarwa Digital",
        "Wio Bank",
        "Ziina Payments",
        "Pyypl Group",
        "Tarabut Gateway",
        "NymCard",
        "Geidea Solutions",
        "HyperPay",
        "Telr Payments",
        "PayTabs",
        "Checkout Middle East",
        "Network Intl",
        "Astra Tech",
        "Botim",
        "Careem Technologies",
        "Swvl Global",
        "Halan",
        "Paymob Solutions",
        "Valu Egypt",
        "Khazna Tech",
        "Flapkap",
        "Sprints",
    ],

    # ── Wave 3 (2026-09-12) ────────────────────────────────────────────────
    # Added to push the registry toward ~1,000 confirmed boards, because the
    # 3-day freshness target scales with the number of employer boards, not
    # with anything clever in the sync. Candidates only: every one is tested
    # against each platform's public endpoint and kept only if a live board
    # answers, so a name that uses Workday, Naukri or nothing at all simply
    # drops out here.
    "in_wave3": [
        "Jar", "Fi Money", "Navi", "Kissht", "MoneyTap", "KreditBee", "Axio",
        "Fibe", "Indifi", "Lendingkart", "Aye Finance", "Vivriti Capital",
        "Yubi", "Rupifi", "FlexiLoans", "Progcap", "Arya ag", "DeHaat",
        "Ninjacart", "WayCool", "Absolute", "Stellapps", "Cropin", "Fasal",
        "Jai Kisan", "Samunnati", "Captain Fresh", "Licious Foods", "FreshToHome",
        "Zappfresh", "EatFit", "Rebel Foods", "Wow Momo", "Chaayos", "Third Wave Coffee",
        "Blue Tokai", "Sleepy Owl", "Bira 91", "Paper Boat", "Wingreens",
        "The Whole Truth", "Yoga Bar", "Open Secret", "SuperBottoms", "Bombay Shaving Company",
        "Beardo", "The Man Company", "Plum Goodness", "Minimalist", "Dot and Key",
        "Sugar Cosmetics", "Wow Skin Science", "mCaffeine", "Bewakoof", "Snitch",
        "Souled Store", "Newme", "Libas", "Fabindia", "Chumbak", "Wakefit",
        "Sleepy Cat", "Pepperfry", "HomeLane", "Livspace", "Interior Company",
        "Nobroker", "Square Yards", "Housing com", "PropTiger", "Stanza Living",
        "Colive", "Zolo Stays", "Isprava", "Smartworks", "Awfis", "Innov8",
        "Simpl", "LazyPay", "Mobikwik", "Freecharge", "Payed", "Decentro",
        "Karza", "IDfy", "Bureau ID", "HyperVerge", "Vernacular ai", "Skit ai",
        "Haptik", "Verloop", "Locobuzz", "Konnect Insights", "Sprinklr India",
        "Wittypen", "Pepper Content", "Animaker", "Rocketium", "Toch ai",
        "Chalo", "Shuttl", "Vogo", "Bounce", "Yulu", "Ather Energy", "Ultraviolette",
        "River Mobility", "Simple Energy", "Euler Motors", "Altigreen", "BluSmart",
        "Zypp Electric", "Battery Smart", "Log9 Materials", "Ola Cell", "Exponent Energy",
        "Agnikul", "Skyroot", "Pixxel", "Dhruva Space", "Bellatrix Aerospace",
        "Digantara", "Astrogate", "TakeMe2Space", "GalaxEye", "SatSure",
        "Wobot ai", "Detect Technologies", "Flytbase", "Ideaforge", "Garuda Aerospace",
        "Aereo", "Asteria Aerospace", "Newspace Research", "Tonbo Imaging",
        "Ather Labs", "Sarvam AI", "Krutrim", "CoRover", "Gnani ai", "Gan ai",
        "Neysa", "E2E Networks", "Jarvislabs", "Nodeshift", "Tessell", "Hasura India",
        "Atlan", "Devtron", "Facets cloud", "Qure ai", "SigTuple", "Niramai",
        "Tricog", "Dozee", "Pristyn Care", "MediBuddy", "Practo", "Docsapp",
        "HealthifyMe", "Cure Foods", "Truemeds", "PharmEasy", "Tata 1mg",
        "Onsurity", "Plum Insurance", "Ditto Insurance", "Turtlemint", "RenewBuy",
        "InsuranceDekho", "Acko", "Digit Insurance", "Kenko", "Even Healthcare",
    ],
    "saas_wave3": [
        "Zluri", "Spendflo", "Nanonets", "Docsumo", "Infrrd", "Klippa",
        "Rossum", "Instabase", "Hyperscience", "Eigen Technologies", "Sensible",
        "Airbyte", "Fivetran", "Census", "Hightouch", "Rudderstack", "Segment",
        "Amplitude", "Mixpanel", "Heap", "PostHog", "June so", "Statsig",
        "LaunchDarkly", "Split io", "Optimizely", "Unleash", "Flagsmith",
        "Temporal", "Inngest", "Trigger dev", "Zeplo", "Hookdeck", "Svix",
        "Knock", "Courier", "Novu", "OneSignal", "Customer io", "Braze",
        "Iterable", "Klaviyo", "Attentive", "Postscript", "Emotive",
        "Vercel", "Netlify", "Render", "Railway", "Fly io", "Northflank",
        "Porter Run", "Qovery", "Koyeb", "Zeabur", "Cyclic", "Deno",
        "Bun", "Turso", "Neon", "PlanetScale", "Xata", "Supabase", "Nhost",
        "Appwrite", "Convex", "InstantDB", "ElectricSQL", "PowerSync",
        "Clerk", "WorkOS", "Stytch", "Descope", "Kinde", "SuperTokens",
        "Ory", "FusionAuth", "Frontegg", "PropelAuth", "Corbado",
        "Retool", "Appsmith", "Budibase", "ToolJet", "Superblocks", "Internal io",
        "Baserow", "NocoDB", "Rowy", "Glide", "Softr", "Stacker", "Noloco",
        "Linear", "Height", "Shortcut", "Teamwork", "Nifty", "Hive", "Wrike",
        "Coda", "Almanac", "Slite", "Nuclino", "Tettra", "Guru", "Slab",
        "Mem", "Reflect", "Tana", "Capacities", "Anytype", "Logseq",
        "Grain", "Fathom Video", "Fireflies ai", "Otter ai", "Read ai", "Avoma",
        "Gong", "Chorus ai", "Clari", "Outreach", "Salesloft", "Apollo io",
        "Clay", "Instantly ai", "Smartlead", "Lemlist", "Reply io", "Woodpecker",
        "Warmly", "Common Room", "Pocus", "Endgame", "Correlated",
    ],
    "global_wave3": [
        "Stripe", "Plaid", "Modern Treasury", "Mercury", "Ramp", "Brex",
        "Navan", "Rippling", "Deel", "Remote com", "Oyster HR", "Velocity Global",
        "Papaya Global", "Multiplier", "Skuad", "Globalization Partners",
        "Gusto", "Justworks", "TriNet", "Zenefits", "Lattice", "Culture Amp",
        "15Five", "Leapsome", "Personio", "HiBob", "Factorial", "Charlie HR",
        "Greenhouse Software", "Lever Inc", "Ashby HQ", "Gem com", "Dover",
        "Findem", "Eightfold ai", "SeekOut", "hireEZ", "Paradox ai", "Sense HQ",
        "Checkr", "Certn", "Vetty", "Veremark", "Zinc Work",
        "Figma", "Canva", "Framer", "Webflow", "Spline", "Rive", "Lottie Files",
        "Miro", "Mural", "FigJam", "Whimsical", "Excalidraw", "tldraw",
        "Notion", "Airtable", "Monday com", "ClickUp", "Asana", "Basecamp",
        "Zapier", "Make com", "Workato", "Tray io", "Pipedream", "n8n",
        "Datadog", "Grafana Labs", "New Relic", "Honeycomb io", "Lightstep",
        "Sentry", "Rollbar", "Bugsnag", "Better Stack", "Checkly", "Cronitor",
        "HashiCorp", "Pulumi", "Spacelift", "env0", "Terrateam", "Digger",
        "Snyk", "Semgrep", "Socket dev", "Chainguard", "Sysdig", "Aqua Security",
        "Wiz io", "Orca Security", "Lacework", "Panther Labs", "Material Security",
        "1Password", "Bitwarden", "Dashlane", "Keeper Security", "Tailscale",
        "Cloudflare", "Fastly", "Bunny net", "Akamai", "Imperva",
        "Anthropic", "OpenAI", "Cohere", "Mistral AI", "Hugging Face",
        "Replicate", "Together AI", "Modal Labs", "Baseten", "Anyscale",
        "Weights and Biases", "Comet ML", "Neptune ai", "LangChain", "LlamaIndex",
        "Pinecone", "Weaviate", "Qdrant", "Chroma", "Milvus", "Vespa ai",
        "Scale AI", "Labelbox", "Snorkel AI", "Surge AI", "Toloka",
        "Perplexity AI", "You com", "Glean", "Dust tt", "Sana Labs",
        "ElevenLabs", "AssemblyAI", "Deepgram", "Speechmatics", "Rev com",
        "Runway ML", "Pika Labs", "Luma AI", "Synthesia", "HeyGen", "Descript",
    ],
    "eu_wave3": [
        "Klarna", "Revolut", "Monzo", "Starling Bank", "N26", "Bunq", "Qonto",
        "Pleo", "Spendesk", "Payhawk", "Moss", "Soldo", "Wise", "Remitly",
        "SumUp", "Mollie", "Adyen", "Checkout com", "Rapyd", "Paddle",
        "GoCardless", "TrueLayer", "Tink", "Yapily", "Salt Edge",
        "Spotify", "SoundCloud", "Bolt", "FREE NOW", "Cabify", "Getir",
        "Gorillas", "Flink", "Picnic", "HelloFresh", "Gousto", "Marley Spoon",
        "Trade Republic", "Scalable Capital", "eToro", "Nutmeg", "Moneyfarm",
        "Zalando", "About You", "Vinted", "Depop", "Back Market", "Wallapop",
        "Contentful", "Storyblok", "Sanity io", "Strapi", "Prismic", "Hygraph",
        "Algolia", "Meilisearch", "Typesense", "Elastic", "OpenSearch",
        "Doctolib", "Alan", "Ada Health", "Kry", "Babylon Health", "Oura",
        "Ledger", "Bitpanda", "Coinbase", "Kraken", "Gemini Trust",
        "UiPath", "Celonis", "Signavio", "Camunda", "Kong Inc", "Tyk io",
        "Sonar Source", "JetBrains", "Gitpod", "Coder com", "Sourcegraph",
        "Grammarly", "DeepL", "Lokalise", "Phrase", "Crowdin", "Smartling",
    ],
}


def all_names():
    """[(display_name, region), ...] with duplicates removed, order preserved."""
    seen, out = set(), []
    for region, names in CANDIDATES.items():
        region = region.replace('_expanded', '').replace('_wave3', '')
        for n in names:
            k = n.lower()
            if k not in seen:
                seen.add(k)
                out.append((n, region))
    return out
